services:
  backend: 
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - ollama
      - qdrant
    ports:
      - 5000:5000
  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d 
  admin: 
    image: adminer
    ports:
      - 8080:8080
  ollama:
   image: ollama/ollama
   ports: 
    - 11434:11434
   #command: 
   # - ollama run mistral
   volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
   environment:
      - OLLAMA_HOST=0.0.0.0
   entrypoint: ["/bin/bash", "/entrypoint.sh"]
  qdrant:
    image:  qdrant/qdrant
    ports:
      - 6333:6333

  frontend:
    build:
      context: ./Frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - ollama
      - qdrant
      - backend
    ports:
      - 3000:3000

volumes:
  ollama_data:
